### ISSUE TITLE
Sourcemaps showing incorrect source files

### ISSUE THREAD

**Issue by ratherblue** [postcss/postcss-cli#260] opened 2019-01-07 23:28 UTC
Not sure if this is a bug or just an issue with how my script is written.  Any help would be greatly appreciated since I've been trying to get this working for several hours now. 

I'm trying to do a pure command-line build using node-sass and postcss with autoprefixer. Source maps work correctly in the node-sass build, but get buggy when postcss is involved. 

I've tried about a dozen different configuration options and the same issues occurred each time.  I made a repo here reproducing the issue: https://github.com/ratherblue/scss-sourcemaps.

## This works (no postcss)
This generates source maps correctly (`_a.scss`, `_b.scss`, and `_c.scss` are correctly mapped):
```
node-sass src/scss/styles.scss dist/styles.css --source-map-embed
```
<img width="428" alt="screen shot 2019-01-07 at 2 35 01 pm" src="https://user-images.githubusercontent.com/993432/50798303-c452e880-128c-11e9-9355-8629176a4d13.png">

## This doesn't work (postcss with/without autoprefixer)
This doesn't generate source maps correctly:
`node-sass src/scss/styles.scss dist/styles.css --source-map-embed && postcss dist/styles.css --use autoprefixer --output dist/styles.css`

<img width="428" alt="screen shot 2019-01-07 at 2 33 25 pm" src="https://user-images.githubusercontent.com/993432/50798446-3c211300-128d-11e9-803f-4c9cc48e880d.png">

This also doesn't generate source maps correctly (postcss but no autoprefixer):
`node-sass src/scss/styles.scss dist/styles.css --source-map-embed && postcss dist/styles.css --output dist/styles.css`

<img width="429" alt="screen shot 2019-01-07 at 3 03 50 pm" src="https://user-images.githubusercontent.com/993432/50798528-886c5300-128d-11e9-80f1-c34b43ce9d97.png">

## Things I've also tried...
* Using the `-m` flag doesn't help (same issue)
* Commenting out bootstrap, e.g. `//@import '../../node_modules/bootstrap/scss/bootstrap';` makes the source maps render as expected, yet when I remove autoprefixer and include bootstrap the source maps are correct so I don't think it's related to bootstrap
* I tried piping in the data instead of saving to a separate file first, and that had the same issues
* Tried downgrading to postcss-cli 6.0.0 and had the same issue
* Experiencing same issue with trying to generate external source maps as well

Any help would be appreciated, thank you!

**Comment by RyanZim** [comment] 2019-01-07 23:38
This would seem to be a postcss issue; not specific to postcss-cli. @ai any ideas?

**Comment by ai** [comment] 2019-01-08 10:53
@RyanZim yeap, it is PostCSS core related issue.

@ratherblue sorry, SCSS → PostCSS source map issues are not high priority right now (but I will accept PR of course). Use PostCSS-based preprocessors (like PreCSS) to have good source map support and better performance.

**Comment by leethinkiq** [comment] 2019-01-08 19:15
@RyanZim @ai I dug into the `postcss` source code and also mozilla's `source-map` code and I believe the issue is actually with how `node-sass` is generating their source maps. `postcss` correctly loads in the previously-generated source map, but some source files get lost when `applySourceMap` is called, probably because `source-map` is expecting source maps to be a certain way and `node-sass` isn't providing them correctly.

I downgraded my version of node-sass to 4.0.0 and the source maps work as expected. Looks like something broke between now and 2 years ago. I don't have time to narrow it down the exact version but there's nothing wrong with postcss. Thanks for replying to my issue and if I have an update I'll add a comment.

**Comment by ratherblue** [comment] 2019-01-08 19:31
@RyanZim @ai I dug into the `postcss` source code and also mozilla's `source-map` code and I believe the issue is actually with how `node-sass` is generating their source maps. `postcss` correctly loads in the previously-generated source map, but some source files get lost when `applySourceMap` is called, probably because `source-map` is expecting source maps to be a certain way and `node-sass` isn't providing them correctly.

I downgraded my version of node-sass to 4.0.0 and the source maps work as expected. Looks like something broke between now and 2 years ago. I don't have time to narrow it down the exact version but there's nothing wrong with postcss. Thanks for replying to my issue and if I have an update I'll add a comment.

**Comment by RyanZim** [comment] 2019-01-08 20:57
Thanks for the update; closing for now.

**Closed by RyanZim** 2019-01-08 20:57 UTC

**Comment by ratherblue** [comment] 2019-01-08 21:03
In case anyone else sees this, node-sass@4.7.2 source maps works with postcss and source maps break with postcss after node-sass@4.8.1.
