### ISSUE TITLE
glob pattern string required

### ISSUE THREAD

**Issue by maliyshock** [postcss/postcss-cli#34] opened 2016-07-31 11:56 UTC
Hey everyone. Have this issue on my windows system. This issue does not apper on nix - based systems.

I`ve installed postcss and postcss-cli, cause i need to run npm scripts from terminal.
So, my package.json looks like this http://joxi.ru/4AkvbE1fMzeaj2
U can see the error on screenshot higher.
When i remove this part "| postcss --use autoprefixer --autoprefixer.browsers 'last 2 versions'" - all is work fine, but without autoprefixier - so this is sad. Can u help me with that?

**Comment by RyanZim** [comment] 2016-08-10 15:39
I can't see your screenshot. Can you paste your package.json here?

**Comment by maliyshock** [comment] 2016-08-18 16:37
https://github.com/maliyshock/flexboxgrid

package json from this repo

**Comment by maliyshock** [comment] 2016-08-18 16:38
{
  "name": "flexboxgrid",
  "version": "1.0.0",
  "description": "Flexbox Grid\r ===========",
  "main": "index.js",
  "dependencies": {
    "autoprefixer": "^6.3.7",
    "clean-css": "^3.4.19",
    "node-sass": "^3.8.0",
    "postcss": "^5.1.0",
    "postcss-cli": "^2.5.2"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "sass": "npm run sass:compile && npm run sass:min",
    "sass:compile": "node-sass dev/scss/index.scss | postcss --use autoprefixer --autoprefixer.browsers 'last 2 versions' > dev/css/my-flex-box-grid.css",
    "sass:min": "cleancss dev/css/my-flex-box-grid.css > dev/css/my-flex-box-grid.min.css"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/maliyshock/flexboxgrid.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/maliyshock/flexboxgrid/issues"
  },
  "homepage": "https://github.com/maliyshock/flexboxgrid#readme"
}

**Comment by maliyshock** [comment] 2016-08-18 16:40
On mac - all works fine. The proplem exist on windows, may be this is particular case

**Comment by RyanZim** [comment] 2016-08-18 17:07
OK, I think the issue is at https://github.com/postcss/postcss-cli/blob/master/index.js#L87. postcss-cli calls globby even if there are no files specified. In your case, you passing the css through stdin, and for some reason that causes an error.

If my hunch is correct, this is a bug (though I can't test on windows; it works on linux). I'll try to make a patch soon.

CC: @watilde @pirxpilot

**Comment by RyanZim** [comment] 2016-08-18 17:32
@maliyshock OK, try this:

In your repository, run:
```
npm uninstall postcss-cli
npm install ryanzim/postcss-cli#3951bd28676ba02d80d45e64cf6240e04f15a9aa
```

Try running your script again and see if it throws an error. Report your findings here.

Delete `node_modules` and run `npm install` to get your project back to where you started.

**Comment by maliyshock** [comment] 2016-08-18 17:34
Thanks. So i have bought a mac, and now i have no any problems with that bug))

**Comment by RyanZim** [comment] 2016-08-18 18:51
@maliyshock Can you close this? Thanks!

**Closed** 2016-08-18 18:52 UTC

**Comment by cxcorp** [comment] 2017-05-05 09:57
Issue is still present in postcss-cli 3.2.0 on Windows 7 x64, node v7.10.0:

```
> postcss --use autoprefixer --autoprefixer.browsers 'last 2 versions, IE >= 10, iOS >= 7' --output generated/styles/main.css generated/styles/main.css

TypeError: patterns must be a string or an array of strings
    at assertPatternsInput (C:\Users\xxx\Documents\Software\yyy\node_modules\postcss-cli\node_modules\globby\index.js:20:9)
    at generateGlobTasks (C:\Users\xxx\Documents\Software\yyy\node_modules\postcss-cli\node_modules\globby\index.js:26:2)
    at module.exports (C:\Users\xxx\Documents\Software\yyy\node_modules\postcss-cli\node_modules\globby\index.js:62:15)
    at Promise.resolve.then (C:\Users\xxx\Documents\Software\yyy\node_modules\postcss-cli\index.js:170:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
```

**Comment by RyanZim** [comment] 2017-05-05 12:45
`--autoprefixer.browsers` options are not supported in v3. Also, please place your input filename first in the command.

**Comment by 42x42x42** [comment] 2018-05-24 15:18
have the same problem on windows 7 x64
How to solve it?

`{
  "name": "natours",
  "version": "1.0.0",
  "description": "landing page for tour company",
  "main": "index.js",
  "scripts": {
    "watch:sass": "node-sass sass/main.scss css/style.css -w",
    "compile:sass": "node-sass sass/main.scss css/style.comp.css",
    "concat:css": "concat -o css/style.concat.css css/style.comp.css css/icon-font.css",
    "prefix:css": "postcss --use autoprefixer -b 'last 10 versions' css/style.concat.css -o css/style.prefix.css"
  },
  "author": "42",
  "license": "ISC",
  "devDependencies": {

    "autoprefixer": "^8.5.0",
    "concat": "^1.0.3",
    "node-sass": "^4.9.0",
    "postcss-cli": "^5.0.0"
  }

}
`
